# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(15)),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name=django.core.validators.MinLengthValidator(5)),
        ),
    ]
