# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180324_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='email',
            new_name='desc',
        ),
    ]
